version: "3"

services:
  app:
    build:
      context: app
    container_name: app
    tty: true
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./database:/docker-entrypoint-initdb.d # Mapeia o diretório database local para o diretório de scripts de inicialização do MySQL
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306 # Mapeia a porta 3306 do contêiner MySQL para o host para permitir conexões externas ao banco de dados.

volumes:
  mysql:
    driver: local
